services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ollama  # Asegura que Ollama esté iniciado antes que la app
    volumes:
      - Z:/data:/app/data
      - Z:/config:/app/config
      - Z:/logs:/app/logs

  ollama:
    image: ollama/ollama:latest  # Usa la imagen de Ollama que ya tienes
    ports:
      - "11434:11434"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
